#!/bin/bash
################################################################################
#
################################################################################

# echo "Preinstall file - Runs before installation"

echo "Performing basic prerequisite checks ..."

# User odoo shouldn't exist or should have been created by the Odoo installation
# procedures such as via the deb-package
grep --quiet -E '/home/odoo:' /etc/passwd    # Indication odoo user have been
                                            # created the wrong way.
if [ $? -eq 0 ]; then
    echo "Warning! An odoo user seems to be present with the wrong home folder."
    echo "This user might conflict with the Odoo 14 installation process."
    echo "Exiting..."
    exit 1
fi


## End
exit 0 # 0 = success
